---
- name: Ansible get Artifact and deploy package to Tomcat server 
  hosts: all
  gather_facts: True
  become_user: root
  become_method: yes
  #vars_prompt:
  #  - name: artifact
  #    prompt: "What artifact do you want to download?"
  #    private: no
  
  roles:
    - { role: tomcat }
