---
- name: Creating an Execution-Group directory
  file:
    path: /opt/tomcat/tomcat9/ "{{ EG }}"
    mode: 0777
    state: directory
    
- name: Retriving package from Artifactory
  get_url: 
    url: http://192.168.0.17:8081/artifactory/webapp/#/artifacts/browse/tree/General/lib-release-repo/ "{{ artifact }}"
    dest: /opt/tomcat/tomcat9/webapps/ "{{ EG }}"
    mode: 0644
