name: GitHub Actions Test
on:
  push:
    branches: [ dev ]
jobs:
  Explore-GitHub-Actions:
    runs-on: [ ubuntu-latest ]
    container:
      image: najite/gitlab-runner:latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
        
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
